spring.application.name=paisafy-backend

# Database Configuration (MongoDB)
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/paisafy}
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
app.jwt.secret=secretKeyMustBeLongEnoughForHS512AlgorithmKeepItSafe
app.jwt.expiration=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=paisafyltd@gmail.com
spring.mail.password=myux fgpn jdnw lbql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
